spring:
  ai:
    dashscope:
      api-key: ${DASHSCOPE_API_KEY}
    mcp:
      client:
        request-timeout: 60000
        stdio:
          servers-configuration: classpath:/mcp/mcp-servers-config.json
#        sse:
#          connections:
#            user-info:
#              url: http://127.0.0.1:8088/sse
logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  level:
    io:
      modelcontextprotocol:
        client: DEBUG
        spec: DEBUG
#spring:
#  ai:
#    dashscope:
#      api-key: ${DASHSCOPE_API_KEY}
#      read-timeout: 120000
#logging:
#  level:
#    org.springframework.ai.chat.client.advisor: debug
#  pattern:
#    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
#    file: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
