spring:
  ai:
    dashscope:
      api-key: ${DASHSCOPE_API_KEY}
      embedding:
        options:
          model: text-embedding-v3
          dimensions: 512
#    vectorstore:
#      #      redis:
#      #        initialize-schema: true    # 是否自动创建索引结构
#      #        index-name: spring-ai-index   # 向量索引名称
#      #        prefix: "embedding:"     # Redis Key 前缀
#      pinecone:
#        api-key: ${PINECONE_API_KEY}
#        index-name: pinecone-inde
#
#  data:
#    redis:
#      url: redis://127.0.0.1:6379
logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"